"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TrackPlaylist = exports.TrackLiked = exports.TrackGenre = exports.TrackArtist = exports.AlbumGenre = exports.AlbumArtist = exports.Album = exports.Artist = exports.Genre = exports.Liked = exports.Playlist = exports.Track = exports.User = void 0;
require("../config/db.config");
const album_model_1 = require("./album.model");
Object.defineProperty(exports, "Album", { enumerable: true, get: function () { return album_model_1.Album; } });
const albumArtist_model_1 = require("./albumArtist.model");
Object.defineProperty(exports, "AlbumArtist", { enumerable: true, get: function () { return albumArtist_model_1.AlbumArtist; } });
const albumGenre_model_1 = require("./albumGenre.model");
Object.defineProperty(exports, "AlbumGenre", { enumerable: true, get: function () { return albumGenre_model_1.AlbumGenre; } });
const artist_model_1 = require("./artist.model");
Object.defineProperty(exports, "Artist", { enumerable: true, get: function () { return artist_model_1.Artist; } });
const genre_model_1 = require("./genre.model");
Object.defineProperty(exports, "Genre", { enumerable: true, get: function () { return genre_model_1.Genre; } });
const liked_model_1 = require("./liked.model");
Object.defineProperty(exports, "Liked", { enumerable: true, get: function () { return liked_model_1.Liked; } });
const playlist_model_1 = require("./playlist.model");
Object.defineProperty(exports, "Playlist", { enumerable: true, get: function () { return playlist_model_1.Playlist; } });
const track_model_1 = require("./track.model");
Object.defineProperty(exports, "Track", { enumerable: true, get: function () { return track_model_1.Track; } });
const trackArtist_model_1 = require("./trackArtist.model");
Object.defineProperty(exports, "TrackArtist", { enumerable: true, get: function () { return trackArtist_model_1.TrackArtist; } });
const trackGenre_model_1 = require("./trackGenre.model");
Object.defineProperty(exports, "TrackGenre", { enumerable: true, get: function () { return trackGenre_model_1.TrackGenre; } });
const trackLiked_model_1 = require("./trackLiked.model");
Object.defineProperty(exports, "TrackLiked", { enumerable: true, get: function () { return trackLiked_model_1.TrackLiked; } });
const trackPlaylist_model_1 = require("./trackPlaylist.model");
Object.defineProperty(exports, "TrackPlaylist", { enumerable: true, get: function () { return trackPlaylist_model_1.TrackPlaylist; } });
const user_model_1 = require("./user.model");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return user_model_1.User; } });
user_model_1.User.hasOne(liked_model_1.Liked);
liked_model_1.Liked.belongsTo(user_model_1.User);
user_model_1.User.hasMany(playlist_model_1.Playlist);
playlist_model_1.Playlist.belongsTo(user_model_1.User);
album_model_1.Album.hasMany(track_model_1.Track);
track_model_1.Track.belongsTo(album_model_1.Album);
liked_model_1.Liked.belongsToMany(track_model_1.Track, { through: trackLiked_model_1.TrackLiked });
track_model_1.Track.belongsToMany(liked_model_1.Liked, { through: trackLiked_model_1.TrackLiked });
playlist_model_1.Playlist.belongsToMany(track_model_1.Track, { through: trackPlaylist_model_1.TrackPlaylist });
track_model_1.Track.belongsToMany(playlist_model_1.Playlist, { through: trackPlaylist_model_1.TrackPlaylist });
track_model_1.Track.belongsToMany(artist_model_1.Artist, { through: trackArtist_model_1.TrackArtist });
artist_model_1.Artist.belongsToMany(track_model_1.Track, { through: trackArtist_model_1.TrackArtist });
genre_model_1.Genre.belongsToMany(track_model_1.Track, { through: trackGenre_model_1.TrackGenre });
track_model_1.Track.belongsToMany(genre_model_1.Genre, { through: trackGenre_model_1.TrackGenre });
album_model_1.Album.belongsToMany(artist_model_1.Artist, { through: albumArtist_model_1.AlbumArtist });
artist_model_1.Artist.belongsToMany(album_model_1.Album, { through: albumArtist_model_1.AlbumArtist });
album_model_1.Album.belongsToMany(genre_model_1.Genre, { through: albumGenre_model_1.AlbumGenre });
genre_model_1.Genre.belongsToMany(album_model_1.Album, { through: albumGenre_model_1.AlbumGenre });
exports.default = { User: user_model_1.User, Track: track_model_1.Track, Playlist: playlist_model_1.Playlist, Liked: liked_model_1.Liked, Genre: genre_model_1.Genre, Artist: artist_model_1.Artist, Album: album_model_1.Album };
//# sourceMappingURL=index.js.map